const axios = require('axios');
const FormData = require('form-data');
const fs = require('fs-extra');
const path = require('path');
const archiver = require('archiver');

class DeploymentService {
  /**
   * Deploy to Vercel
   */
  async deployToVercel(app, vercelToken) {
    try {
      // Create deployment package
      const zipPath = await this.createDeploymentPackage(app);
      
      // Read zip file
      const zipBuffer = await fs.readFile(zipPath);
      
      // Create form data
      const formData = new FormData();
      formData.append('file', zipBuffer, {
        filename: `${app.name}.zip`,
        contentType: 'application/zip'
      });
      formData.append('name', app.name.toLowerCase().replace(/\s+/g, '-'));
      formData.append('projectSettings', JSON.stringify({
        framework: 'create-react-app',
        buildCommand: 'npm run build',
        outputDirectory: 'build',
        installCommand: 'npm install'
      }));

      // Deploy to Vercel
      const response = await axios.post('https://api.vercel.com/v13/deployments', formData, {
        headers: {
          ...formData.getHeaders(),
          Authorization: `Bearer ${vercelToken}`
        }
      });

      // Cleanup
      await fs.remove(zipPath);

      return {
        success: true,
        url: response.data.url,
        deploymentId: response.data.id,
        platform: 'vercel'
      };
    } catch (error) {
      throw new Error(`Vercel deployment failed: ${error.message}`);
    }
  }

  /**
   * Deploy to Netlify
   */
  async deployToNetlify(app, netlifyToken, siteId) {
    try {
      // Create build package
      const zipPath = await this.createDeploymentPackage(app);
      
      // Read zip file
      const zipBuffer = await fs.readFile(zipPath);

      // Deploy to Netlify
      const response = await axios.post(
        `https://api.netlify.com/api/v1/sites/${siteId}/deploys`,
        zipBuffer,
        {
          headers: {
            'Content-Type': 'application/zip',
            Authorization: `Bearer ${netlifyToken}`
          }
        }
      );

      // Cleanup
      await fs.remove(zipPath);

      return {
        success: true,
        url: response.data.deploy_ssl_url || response.data.url,
        deploymentId: response.data.id,
        platform: 'netlify'
      };
    } catch (error) {
      throw new Error(`Netlify deployment failed: ${error.message}`);
    }
  }

  /**
   * Create deployment package (ZIP file)
   */
  async createDeploymentPackage(app) {
    return new Promise(async (resolve, reject) => {
      const tempDir = path.join(__dirname, '../../temp');
      await fs.ensureDir(tempDir);
      
      const zipPath = path.join(tempDir, `deploy-${app._id}-${Date.now()}.zip`);
      const output = fs.createWriteStream(zipPath);
      const archive = archiver('zip', { zlib: { level: 9 } });

      output.on('close', () => resolve(zipPath));
      archive.on('error', reject);

      archive.pipe(output);

      // Add frontend files
      if (app.generatedCode?.frontend?.structure) {
        for (const file of app.generatedCode.frontend.structure) {
          archive.append(file.content || '', { name: `frontend/${file.path}` });
        }
      }

      // Add backend files (if deploying full-stack)
      if (app.generatedCode?.backend?.structure) {
        for (const file of app.generatedCode.backend.structure) {
          archive.append(file.content || '', { name: `backend/${file.path}` });
        }
      }

      // Add package.json
      if (app.generatedCode?.frontend?.dependencies) {
        archive.append(JSON.stringify({
          name: app.name.toLowerCase().replace(/\s+/g, '-'),
          version: '1.0.0',
          private: true,
          dependencies: Object.fromEntries(app.generatedCode.frontend.dependencies),
          scripts: {
            start: 'react-scripts start',
            build: 'react-scripts build',
            test: 'react-scripts test',
            eject: 'react-scripts eject'
          }
        }, null, 2), { name: 'frontend/package.json' });
      }

      // Add README
      archive.append(`# ${app.name}\n\n${app.description || 'Generated by Vibecoders'}\n`, {
        name: 'README.md'
      });

      archive.finalize();
    });
  }

  /**
   * Get deployment status
   */
  async getDeploymentStatus(platform, deploymentId, token) {
    try {
      let url;
      let headers = { Authorization: `Bearer ${token}` };

      if (platform === 'vercel') {
        url = `https://api.vercel.com/v13/deployments/${deploymentId}`;
      } else if (platform === 'netlify') {
        url = `https://api.netlify.com/api/v1/deploys/${deploymentId}`;
      } else {
        throw new Error('Unsupported platform');
      }

      const response = await axios.get(url, { headers });
      return response.data;
    } catch (error) {
      throw new Error(`Failed to get deployment status: ${error.message}`);
    }
  }
}

module.exports = new DeploymentService();

